document.write("<div class=\"formHeader\" align=\"center\">");
document.write("  <h4>Receive <span><i class = \"fa fa-dollar\" aria-hidden=\"true\"></i>100</span> Bonus On Registration</h4>");
document.write("</div>");
document.write("<div class=\"inputWithIcon\">");
document.write("  <input type=\"text\" placeholder=\"Your name\">");
document.write("  <i class=\"fa fa-user fa-lg fa-fw\" aria-hidden=\"true\"></i>");
document.write("</div>");
document.write("<div class=\"inputWithIcon\">");
document.write("  <input type=\"text\" placeholder=\"Phone Number\">");
document.write("  <i class=\"fa fa-phone fa-lg fa-fw\" aria-hidden=\"true\"></i>");
document.write("</div>");
document.write("<div class=\"inputWithIcon\">");
document.write("  <input type=\"text\" placeholder=\"Email\">");
document.write("  <i class=\"fa fa-envelope fa-lg fa-fw\" aria-hidden=\"true\"></i>");
document.write("</div>");
document.write("<div class=\"inputWithIcon\">");
document.write("  <input type=\"text\" placeholder=\"Address\">");
document.write("  <i class=\"fa fa-envelope fa-lg fa-fw\" aria-hidden=\"true\"></i>");
document.write("<div>");
document.write("</div>");
document.write("  <input type=\"submit\" value=\"SUBMIT\" class=\"submit\">");
document.write("</div>");
document.write("<div>");
document.write("  <p style=\"color:#FFFFFF;font-size:10px;\">Note:Please fill correct email and phone number<br> 1:Email add to receive the download link.<br> 2:Mobile number to receive verification info.</p>");
document.write("</div>");
